  const  AuctionItems = [
      {
        title: 'iPhone 11 Pro 128GB space-grey',
        alt: 'iPhone 11 Pro',
        description: "Adventure is never far away",
        ImageUrl: '/assets/images/product/7.jpg',
        DataAction: '/assets/images/product/7.jpg',
        marketPrice: 'TRY 4,000',
        startPrice: 'TRY 400',
        minParticipantsReq: "443",
        minBiddersReq: "500",
        auctionStartTime: "2 days",
        auctionMaxDuration: "1 hour",
        auctionMaxRounds: "10",
        auctionEntryFee: "4 Tokens",
        RoundBiddingFee: "4 Tokens",
        badge: {
          variant: 'info',
          text: 'NEW',
        },
      },
      {
        title: 'Fitbit Versa 2 Special edition - Copper rose',
        alt: 'Fitbit Versa 2 Special edition',
        description: "The Fitbit Versa 2 Special Edition includes a free trial to Fitbit Premium. With a 6 day battery life.",
        ImageUrl: "/assets/images/product/31.jpg",
        DataAction: '/assets/images/product/31.jpg',
        marketPrice: 'TRY 1,700',
        startPrice: 'TRY 900',
        minParticipantsReq: "198",
        minBiddersReq: "300",
        auctionStartTime: "1 day 4 hours",
        auctionMaxDuration: "1 hour",
        auctionMaxRounds: "10",
        auctionEntryFee: "4 Tokens",
        RoundBiddingFee: "4 Tokens",
        badge: {
          variant: 'info',
          text: 'NEW',
        },
      },
      {
        title: 'Fitbit Sense Advanced Smartwatch - Black',
        alt: 'Fitbit Sense Advanced Smartwatch',
        description: "Fitbit Sense Advanced Smartwatch with Tools for Heart Health, Stress Management & Skin Temperature Trends, Alexa Built-in, Carbon/Graphite, One Size (S & L Bands Included) ",
        ImageUrl: '/assets/images/product/12.jpg',
        DataAction: '/assets/images/product/12.jpg',
        marketPrice: 'TRY 2,710',
        startPrice: 'TRY 1,500',
        minParticipantsReq: "200",
        minBiddersReq: "250",
        auctionStartTime: "18 hours",
        auctionMaxDuration: "1 hour",
        auctionMaxRounds: "10",
        auctionEntryFee: "4 Tokens",
        RoundBiddingFee: "4 Tokens",
        badge: {
          variant: 'info',
          text: 'NEW',
        },
      },
      {
        title: 'iPhone 11 Pro 128GB space-grey',
        alt: 'iPhone 11 Pro',
        description: "Adventure is never far away",
        ImageUrl: '/assets/images/product/33.jpg',
        DataAction: '/assets/images/product/33.jpg',
        marketPrice: 'TRY 4,000',
        startPrice: 'TRY 400',
        minParticipantsReq: "443",
        minBiddersReq: "500",
        auctionStartTime: "2 days",
        auctionMaxDuration: "1 hour",
        auctionMaxRounds: "10",
        auctionEntryFee: "4 Tokens",
        RoundBiddingFee: "4 Tokens",
        badge: {
          variant: 'info',
          text: 'NEW',
        },
      }
    ]

    export default AuctionItems;